In [4]:
import numpy as np


In [10]:
l = ([[1,2],[3,4]])

In [10]:
print (l)

[[1, 2], [3, 4]]


In [12]:
ar = np.array(l)

In [14]:
print(ar)

[[1 2]
 [3 4]]


In [16]:
tw = np.asarray(l)

In [18]:
print(tw)

[[1 2]
 [3 4]]


In [20]:
te = np.asanyarray(l)
print(te)

[[1 2]
 [3 4]]


In [22]:
m = np.matrix(l)

In [24]:
print(m)

[[1 2]
 [3 4]]


In [30]:
np.fromfunction(lambda i,j : i != j ,(3,3))

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [32]:
np.fromfunction(lambda i,j : i*j,(2,3))

array([[0., 0., 0.],
       [0., 1., 2.]])

In [38]:
a = np.fromfunction(lambda i,j : i+j,(4,6))
print(a)

[[0. 1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7. 8.]]


In [42]:
print(a.dtype)

float64


In [54]:
arr = (i*i for i in range(5))
np.fromiter(arr,int)

array([ 0,  1,  4,  9, 16])

In [74]:
ar = np.fromstring("256 741 8", sep = ' ')
print(ar)

[256. 741.   8.]


In [76]:
ar.ndim

1

In [90]:
ar2 = np.array([[1,2,3],[4,8,7],[8,7,7]])
print(ar2)

[[1 2 3]
 [4 8 7]
 [8 7 7]]


In [92]:
ar2.ndim

2

In [12]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
list1 = [1,2]
a1= np.array(list1)
list2 = [4,5]
a2 = np.array(list2)
print(a1+a2)
print(list1+list2)

[5 7]
[1, 2, 4, 5]


In [22]:
list1 = [1,2]
list2 = [4,5]
print(list1+list2)



[1, 2, 4, 5]


In [24]:
a1@a2

14

In [26]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[1,2],[3,4]])

In [28]:
a1@a2

array([[ 7, 10],
       [15, 22]])

In [30]:
arr = np.random.randint(3,100,(3,4))
print(arr)


[[56 71 55 38]
 [14 85 43 77]
 [14 70 74 75]]


In [32]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
s = np.random.rand(3,4)
print(s)
s.reshape(6,2)


[[0.44865202 0.70780243 0.07942247 0.06173385]
 [0.56094532 0.11557513 0.7715457  0.0587752 ]
 [0.29077686 0.23956288 0.32987388 0.79029406]]


array([[0.44865202, 0.70780243],
       [0.07942247, 0.06173385],
       [0.56094532, 0.11557513],
       [0.7715457 , 0.0587752 ],
       [0.29077686, 0.23956288],
       [0.32987388, 0.79029406]])

In [38]:
s[1]

array([0.56094532, 0.11557513, 0.7715457 , 0.0587752 ])

In [42]:
s[1][1]

0.11557513260631425

In [44]:
s>0.5

array([[False,  True, False, False],
       [ True, False,  True, False],
       [False, False, False,  True]])

In [46]:
aq = s>0.5
print(aq)

[[False  True False False]
 [ True False  True False]
 [False False False  True]]


In [50]:
s[s>0.5]

array([0.70780243, 0.56094532, 0.7715457 , 0.79029406])

In [2]:
s[0:2,[1,2]]

NameError: name 's' is not defined