In [2]:
import numpy as np

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,4,1]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 4 1]]


In [16]:
a.T

array([[1, 4, 7],
       [2, 5, 4],
       [3, 6, 1]])

In [18]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 4, 1])

In [24]:
b = np.expand_dims(a,axis=1)
b
b.ndim

3

In [30]:
b = np.squeeze(b)
b.ndim


2

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr1)

[1 2 3 4 5 6 7 8 9 0]


In [51]:
arr2= np.expand_dims(arr1,axis=1)

In [63]:
arr3 = np.expand_dims(arr2,axis=2)

In [71]:
arr4 = np.expand_dims(arr2,axis=2)
arr4.ndim

3

In [75]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9, 0, 0, 0])

In [77]:
np.roll(arr1,2)

array([9, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [78]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a1|a2

array([[ 5,  6],
       [ 7, 12]])

In [87]:
~(a1|a2)

array([[ -6,  -7],
       [ -8, -13]])

In [30]:
str = np.array(["mayank","dewali","##9"])

In [32]:
np.char.upper(str)

array(['MAYANK', 'DEWALI', '##9'], dtype='<U6')

In [34]:
np.char.islower(str)

array([ True,  True, False])

In [36]:
np.char.isalnum(str)

array([ True,  True, False])

In [24]:
np.sqrt(26)

5.0990195135927845

In [46]:
num = np.array([100,200,200,300,400])
np.sqrt(num)

array([10.        , 14.14213562, 14.14213562, 17.32050808, 20.        ])

In [52]:
np.mean(num)


240.0

In [54]:
np.median(num)

200.0

In [58]:
np.std(num)

101.9803902718557

In [62]:
np.sort(num)

array([100, 200, 200, 300, 400])

In [74]:
np.searchsorted(num,400)

4

In [76]:
np.count_nonzero(str)

3

In [102]:
z1 = np.sort(a1)

In [104]:
np.searchsorted(z1[0],2)

1

In [108]:
np.where(num>3)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [112]:
a = num.view()
a[0] = 500
print(a,num)

[500 200 200 300 400] [500 200 200 300 400]


In [116]:
a = num.copy()
a[0] = 400
print(a,num)

[400 200 200 300 400] [500 200 200 300 400]


In [2]:
list(range(5))

[0, 1, 2, 3, 4]